/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicComboBoxRenderer;
import javax.swing.plaf.basic.BasicComboBoxUI;
import logica.Controladora;
import logica.Rol;
import logica.Usuario;

/**
 *
 * @author leand
 */
public class CrearUser extends javax.swing.JFrame {
Controladora control;
Usuario usr;
int xMouse, yMouse;
    /**
     * Creates new form CrearUser
     */
    public CrearUser(Controladora control, Usuario usr) {
        initComponents();
        this.control = control;
this.usr = usr;
        transparencia();
         //para que se cierre solo la ventana al darle a la X
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

         //para que al darle a la X tambien se abra el jframe de verDatos
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Código para abrir otro JFrame al cerrar este
                PrincipalAdmin pantalla = new PrincipalAdmin(control, usr);
                pantalla.setVisible(true);
                pantalla.setLocationRelativeTo(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombreUsuario = new javax.swing.JTextField();
        xUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtContrasena = new javax.swing.JPasswordField();
        xContrasena = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblLimpiar = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        barraX = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 290, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOpaque(true);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 285, 310, -1));

        cmbRol.setBackground(new java.awt.Color(102, 102, 102));
        cmbRol.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cmbRol.setForeground(new java.awt.Color(255, 255, 255));
        cmbRol.setBorder(null);
        cmbRol.setMinimumSize(new java.awt.Dimension(64, 22));
        cmbRol.setOpaque(true);
        cmbRol.setPreferredSize(new java.awt.Dimension(64, 22));
        jPanel1.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 310, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CREAR USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOpaque(true);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 125, 310, -1));

        txtNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreUsuario.setText("Ingrese el nombre de usuario");
        txtNombreUsuario.setBorder(null);
        txtNombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreUsuarioFocusLost(evt);
            }
        });
        txtNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMousePressed(evt);
            }
        });
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        txtNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 310, 30));

        xUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        xUsuario.setForeground(new java.awt.Color(0, 0, 0));
        xUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        xUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(xUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 20, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NOMBRE DE USUARIO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ROL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 205, 310, -1));

        txtContrasena.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(102, 102, 102));
        txtContrasena.setText("contraseña");
        txtContrasena.setBorder(null);
        txtContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContrasenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrasenaFocusLost(evt);
            }
        });
        txtContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContrasenaMousePressed(evt);
            }
        });
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyTyped(evt);
            }
        });
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 310, 30));

        xContrasena.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        xContrasena.setForeground(new java.awt.Color(0, 0, 0));
        xContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        xContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xContrasenaMouseClicked(evt);
            }
        });
        jPanel1.add(xContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 20, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CONTRASEÑA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jPanel6.setBackground(new java.awt.Color(201, 33, 45));

        lblLogin.setBackground(new java.awt.Color(38, 66, 46));
        lblLogin.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Crear");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.setOpaque(true);
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 120, 40));

        jPanel5.setBackground(new java.awt.Color(201, 33, 45));

        lblLimpiar.setBackground(new java.awt.Color(201, 33, 45));
        lblLimpiar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiar.setText("Limpiar");
        lblLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLimpiar.setOpaque(true);
        lblLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 120, 40));

        Panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 480, 400));

        panelBarra.setOpaque(false);
        panelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraMouseDragged(evt);
            }
        });
        panelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraMousePressed(evt);
            }
        });

        barraX.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        barraX.setForeground(new java.awt.Color(0, 0, 0));
        barraX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barraX.setText("X");
        barraX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barraX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barraXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barraXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createSequentialGroup()
                .addGap(0, 510, Short.MAX_VALUE)
                .addComponent(barraX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBarraLayout.setVerticalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraX, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Panel.add(panelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgLoginFondo.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Panel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 500));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
List<Rol> listaRoles = control.traerRoles();
if(listaRoles != null){
    for(Rol rol : listaRoles){
    cmbRol.addItem(rol.getNombreRol());
}
}

    }//GEN-LAST:event_formWindowOpened

    private void barraXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraXMouseClicked
        PrincipalAdmin pantalla = new PrincipalAdmin(control, usr);
        this.dispose();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_barraXMouseClicked

    private void barraXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraXMouseEntered

        barraX.setBackground(new Color (201,33,45));
        barraX.setForeground(Color.WHITE);
        barraX.setOpaque(true);
    }//GEN-LAST:event_barraXMouseEntered

    private void barraXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraXMouseExited
        barraX.setForeground(Color.BLACK);
        barraX.setOpaque(false);
    }//GEN-LAST:event_barraXMouseExited

    private void panelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelBarraMouseDragged

    private void panelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraMousePressed

    private void txtNombreUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreUsuarioFocusGained
        if(txtNombreUsuario.getText().equals("Ingrese el nombre de usuario")){
            txtNombreUsuario.setForeground(Color.BLACK);
            txtNombreUsuario.setText("");
        }
    }//GEN-LAST:event_txtNombreUsuarioFocusGained

    private void txtNombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreUsuarioFocusLost
        if(txtNombreUsuario.getText().equals("")){
            txtNombreUsuario.setForeground(new Color (102,102,102));
            txtNombreUsuario.setText("Ingrese el nombre de usuario");
        }
    }//GEN-LAST:event_txtNombreUsuarioFocusLost

    private void txtNombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMousePressed
        if(txtNombreUsuario.getText().equals("Ingrese el nombre de usuario")){
            txtNombreUsuario.setText("");
            txtNombreUsuario.setForeground(Color.BLACK);
        }
        if(String.valueOf(txtContrasena.getPassword()).isEmpty()){
            txtContrasena.setText("contraseña");
            txtContrasena.setForeground(new Color (102,102,102));
        }

    }//GEN-LAST:event_txtNombreUsuarioMousePressed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtNombreUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyPressed

    }//GEN-LAST:event_txtNombreUsuarioKeyPressed

    private void txtNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyTyped
        xUsuario.setVisible(true);
    }//GEN-LAST:event_txtNombreUsuarioKeyTyped

    private void xUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xUsuarioMouseClicked
        txtNombreUsuario.setText("");
        xUsuario.setVisible(false);
    }//GEN-LAST:event_xUsuarioMouseClicked

    private void txtContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaFocusGained
        if(String.valueOf(txtContrasena.getPassword()).equals("contraseña")){
            txtContrasena.setForeground(Color.BLACK);
            txtContrasena.setText("");}
    }//GEN-LAST:event_txtContrasenaFocusGained

    private void txtContrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaFocusLost
        if(String.valueOf(txtContrasena.getPassword()).equals("")){
            txtContrasena.setForeground(new Color (102,102,102));
            txtContrasena.setText("contraseña");}
    }//GEN-LAST:event_txtContrasenaFocusLost

    private void txtContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrasenaMousePressed
        if(String.valueOf(txtContrasena.getPassword()).equals("contraseña")){
            txtContrasena.setText("");
            txtContrasena.setForeground(Color.BLACK);
        }
        if(txtNombreUsuario.getText().isEmpty()){
            txtNombreUsuario.setText("Ingrese el nombre de usuario");
            txtNombreUsuario.setForeground(new Color (102,102,102));
        }
    }//GEN-LAST:event_txtContrasenaMousePressed

    private void txtContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyTyped
        xContrasena.setVisible(true);
    }//GEN-LAST:event_txtContrasenaKeyTyped

    private void xContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xContrasenaMouseClicked
        txtContrasena.setText("");
        xContrasena.setVisible(false);
    }//GEN-LAST:event_xContrasenaMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
cmbRol.showPopup();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
     String usuario = txtNombreUsuario.getText();
        String contrasena = txtContrasena.getText();
        String rol = (String) cmbRol.getSelectedItem();
        
        control.crearUsuario(usuario, contrasena, rol);
        mostrarMensaje("Se creó el Usuario.", "Info", "Usuario Creado");     
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        lblLogin.setBackground(new Color (84,143,101));
        lblLogin.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        lblLogin.setBackground(new Color (38,66,46));
        lblLogin.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLoginMouseExited

    private void lblLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseClicked
txtContrasena.setText("");
txtNombreUsuario.setText("");
cmbRol.setSelectedIndex(0);
    }//GEN-LAST:event_lblLimpiarMouseClicked

    private void lblLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseEntered

lblLimpiar.setBackground(new Color (201,67,62));
lblLimpiar.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblLimpiarMouseEntered

    private void lblLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseExited
lblLimpiar.setBackground(new Color (201,33,45));
lblLimpiar.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLimpiarMouseExited
public void mostrarMensaje(String mensaje, String tipoMensaje, String titulo){
       JOptionPane optionPane = new JOptionPane(mensaje);
       if(tipoMensaje.equals("Info")){
                   optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);

       }else if(tipoMensaje.equals("Error")){
                   optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);

       }
        JDialog dialog = optionPane.createDialog(titulo);
                dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
  }
public void transparencia(){
    txtNombreUsuario.setOpaque(false);
    txtContrasena.setOpaque(false);
 cmbRol.setOpaque(false);
 cmbRol .setEditable(true);
 // Personalizar el campo de texto del JComboBox
 JTextField boxField = (JTextField)cmbRol .getEditor().getEditorComponent();
   boxField.setBorder(BorderFactory.createEmptyBorder());
   boxField.setForeground(Color.BLACK);
   boxField.setFocusable(false);
   boxField.setOpaque(false);
// Personalizar la flecha del JComboBox
        JButton arrowButton = (JButton) cmbRol.getComponent(0); // Flecha
        arrowButton.setContentAreaFilled(false);
        arrowButton.setFocusPainted(false);
        arrowButton.setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 0));


    xUsuario.setVisible(false);
    xContrasena.setVisible(false);
}
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel barraX;
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblLimpiar;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JLabel xContrasena;
    private javax.swing.JLabel xUsuario;
    // End of variables declaration//GEN-END:variables
}
