/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;
import logica.Controladora;
import logica.Usuario;

/**
 *
 * @author leand
 */
public class LoginInicial extends javax.swing.JFrame {

    Controladora control;
    int xMouse, yMouse;

    /**
     * Creates new form Login
     */
    public LoginInicial() {
        initComponents();
        control = new Controladora();
        transparencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panelBarra = new javax.swing.JPanel();
        barraX = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JTextField();
        xContrasena = new javax.swing.JLabel();
        xUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarra.setOpaque(false);
        panelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraMouseDragged(evt);
            }
        });
        panelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraMousePressed(evt);
            }
        });

        barraX.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        barraX.setForeground(new java.awt.Color(0, 0, 0));
        barraX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barraX.setText("X");
        barraX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barraX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barraXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barraXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createSequentialGroup()
                .addGap(0, 760, Short.MAX_VALUE)
                .addComponent(barraX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBarraLayout.setVerticalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraX, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(panelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgLogin.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 500));

        jPanel3.setBackground(new java.awt.Color(145, 164, 171));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOpaque(true);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 265, 310, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOpaque(true);
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 185, 310, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CONTRASEÑA");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INICIAR SESIÓN");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 270, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("USUARIO");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("Ingrese el nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.setOpaque(true);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 310, 30));

        txtContrasena.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(102, 102, 102));
        txtContrasena.setText("contraseña");
        txtContrasena.setBorder(null);
        txtContrasena.setOpaque(true);
        txtContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContrasenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrasenaFocusLost(evt);
            }
        });
        txtContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContrasenaMousePressed(evt);
            }
        });
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyTyped(evt);
            }
        });
        jPanel3.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 310, 30));

        jPanel5.setBackground(new java.awt.Color(38, 66, 46));

        lblLogin.setBackground(new java.awt.Color(38, 66, 46));
        lblLogin.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("LOGIN");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.setOpaque(true);
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 160, 40));

        txtMensaje.setEditable(false);
        txtMensaje.setBackground(new java.awt.Color(102, 102, 102));
        txtMensaje.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(102, 0, 0));
        txtMensaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMensaje.setBorder(null);
        jPanel3.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 310, -1));

        xContrasena.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        xContrasena.setForeground(new java.awt.Color(0, 0, 0));
        xContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        xContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xContrasenaMouseClicked(evt);
            }
        });
        jPanel3.add(xContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 20, 30));

        xUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        xUsuario.setForeground(new java.awt.Color(0, 0, 0));
        xUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        xUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xUsuarioMouseClicked(evt);
            }
        });
        jPanel3.add(xUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 158, 20, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgLoginFondo.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 200, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("USUARIO");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 550, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void xContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xContrasenaMouseClicked
txtContrasena.setText("");
xContrasena.setVisible(false);
    }//GEN-LAST:event_xContrasenaMouseClicked

    private void xUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xUsuarioMouseClicked
        txtUsuario.setText("");
        xUsuario.setVisible(false);
    }//GEN-LAST:event_xUsuarioMouseClicked

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
      xUsuario.setVisible(true);
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        String usuario = txtUsuario.getText();
        String contrasena = txtContrasena.getText();
        
        Usuario usr = control.validarUsuario(usuario, contrasena);
        if(usr != null){
                    String rol = usr.getRol().getNombreRol();
                    if(rol.equals("admin")){
                        PrincipalAdmin pAdmin = new PrincipalAdmin(control, usr);
                        pAdmin.setVisible(true);
                        pAdmin.setLocationRelativeTo(null);
                        this.dispose();
                    }if(rol.equals("user")){
                        PrincipalUser pUser = new PrincipalUser(control, usr);
                        pUser.setVisible(true);
                        pUser.setLocationRelativeTo(null);
                        this.dispose();
                    }

        }else{
                    txtMensaje.setText("Usuario o contraseña incorrectos.");

        }
    }//GEN-LAST:event_lblLoginMouseClicked

    private void barraXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraXMouseEntered
       
        barraX.setBackground(new Color (201,33,45));
        barraX.setForeground(Color.WHITE);
         barraX.setOpaque(true);
    }//GEN-LAST:event_barraXMouseEntered

    private void panelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraMousePressed

    private void panelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelBarraMouseDragged

    private void barraXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraXMouseClicked
       System.exit(0);
    }//GEN-LAST:event_barraXMouseClicked

    private void barraXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraXMouseExited
       barraX.setForeground(Color.BLACK);
         barraX.setOpaque(false);
    }//GEN-LAST:event_barraXMouseExited

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        lblLogin.setBackground(new Color (38,66,46));
                  lblLogin.setForeground(Color.WHITE);

    }//GEN-LAST:event_lblLoginMouseExited

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
         lblLogin.setBackground(new Color (84,143,101));
          lblLogin.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblLoginMouseEntered

    private void txtContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyTyped
       xContrasena.setVisible(true);
    }//GEN-LAST:event_txtContrasenaKeyTyped

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if(txtUsuario.getText().equals("Ingrese el nombre de usuario")){
           txtUsuario.setText("");
        txtUsuario.setForeground(Color.BLACK); 
        }
        if(String.valueOf(txtContrasena.getPassword()).isEmpty()){
            txtContrasena.setText("contraseña");
            txtContrasena.setForeground(new Color (102,102,102));
        }
        
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrasenaMousePressed
         if(String.valueOf(txtContrasena.getPassword()).equals("contraseña")){
           txtContrasena.setText("");
        txtContrasena.setForeground(Color.BLACK); 
        }
        if(txtUsuario.getText().isEmpty()){
            txtUsuario.setText("Ingrese el nombre de usuario");
            txtUsuario.setForeground(new Color (102,102,102));
        }
    }//GEN-LAST:event_txtContrasenaMousePressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed

    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaFocusGained
 if(String.valueOf(txtContrasena.getPassword()).equals("contraseña")){
     txtContrasena.setForeground(Color.BLACK); 
      txtContrasena.setText("");}
    }//GEN-LAST:event_txtContrasenaFocusGained

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
  if(txtUsuario.getText().equals("Ingrese el nombre de usuario")){
      txtUsuario.setForeground(Color.BLACK); 
      txtUsuario.setText("");
  }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
  if(txtUsuario.getText().equals("")){
      txtUsuario.setForeground(new Color (102,102,102));
      txtUsuario.setText("Ingrese el nombre de usuario");
  }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtContrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaFocusLost
 if(String.valueOf(txtContrasena.getPassword()).equals("")){
     txtContrasena.setForeground(new Color (102,102,102));
      txtContrasena.setText("contraseña");}
    }//GEN-LAST:event_txtContrasenaFocusLost

    /**
     * @param args the command line arguments
     */
public void transparencia(){
    txtUsuario.setOpaque(false);
    txtContrasena.setOpaque(false);
    xUsuario.setVisible(false);
    xContrasena.setVisible(false);
    txtMensaje.setOpaque(false);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraX;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtMensaje;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel xContrasena;
    private javax.swing.JLabel xUsuario;
    // End of variables declaration//GEN-END:variables

 
}
